dist: trusty
sudo: required
language: node_js
node_js:
  - "8"

services:
  - docker

before_install:
  - docker pull ethereum/client-go:latest

env:
  - INTEGRATION=true
  - GETH=true
  - PACKAGES=true

matrix:
  allow_failures:
    - env: GETH=true

install:
  - npm install -g lerna@^3.0.0-beta.21
  - npm install -g yarn
  - npm run bootstrap

script:
  - npm run ci
