os: linux
language: node_js

# configure Travis to run on-push builds only on PR-recipient branches
branches:
  only:
    # long-lived branches
    - master
    - develop
    - next
    # other targets
    - truffle-db

before_install:
  - npm install -g yarn
install:
  - yarn bootstrap
  - truffle obtain --solc=0.5.16

script: yarn ci


jobs:
  fast_finish: true
  include:
    - node_js: 8
      env: FABRICEVM=true
      install:
        - yarn bootstrap
        - truffle obtain --solc=0.5.16
    # WINDOWS -- BEGINNING -- 
    - node_js: 10
      os: windows
      env: 
        # Use YARN_GPG=no so Travis doesn't freeze after finished build
        - YARN_GPG=no WINDOWS=true
      before_install:
        - powershell Set-ExecutionPolicy -ExecutionPolicy unrestricted
        # We hav to use powershell to install geth on windows environment. Git Bash doesn't have package manager.
        - powershell ./scripts/install_geth.ps1
        - npm install -g yarn
      install:
        - yarn bootstrap
    # WINDOWS -- END --
    - node_js: 8
      env: COVERAGE=true
      install:
        - yarn bootstrap
        - truffle obtain --solc=0.5.8
    - if: |
        branch = develop AND \
        type = push
      node_js: 10
      env: COLONY=true
      install:
        - yarn bootstrap
        - truffle obtain --solc=0.5.16
  allow_failures:
      - os: windows
      - env: COVERAGE=true


cache:
  directories:
    - node_modules
    - $(npm config get prefix)/lib/node_modules # globally installed stuff (i.e. lerna)
    - ~/.config/truffle/compilers


notifications:
  slack:
    secure: HtQp66mJVCHPREUWwKCtR6w4uh+lA2N6/Erv+Ea4kObX0XMn13FYE+UsR1dwjF/VB+jNJt9N9nKz0E14zuYl7jsQIyD/vZyZ3nWGeWKfQyVwz79NnYBiwpYo/Y6G6Nb42Aq9Sy5byP5qBbrn+7Yvqs0DiYDy3QhDhC9D5gOXkFVlmAb0RVl+b125YL9SQR0u6GRTFG19kyH1pb2hwGKvKmntKbkmzYztzli/k44Rfoq8y9GPFu8ZXYD9TfxXxDxO7xu6oE+lYZZX1mos2vdRXrgR9J6DtHu4kq9dh+50cn0EOOcG/O4yM0wEP3NZkMsmxsU31w1ezbhYNGHO09sij2di+8k2r6a1QMEMRzTC2ikoUxEf9y+aTrMtRlUacM/vTkOwgYzsYpzdietfQ17VkTpa9k3D1tuVEwNUAsCl5sDpi09QivcLULoWNfsLFXmAxs2Oz71i3BAYIlOnkMmA9rJfat8u1jKWxylQYlPt7aXrhvb7dQkmdv82Nrhk7Oo+nEzaGyfB1GRo598S+o6oSTqnPYCegyrhQSVmlml7afwvA/yahSB6k0Rz5O+JDcK8g6Vn18L9jeNzcHsCUJYyYks+v57hJtCnjBVHJD8JsR996FEkOjcL1/d5xz7NN/iO9ZTIOXl9GfimxCq3Ao7NhinzwLf2tqi2hEGVhYaLL8g=
