name: Node CI

on:
  push:
    branches:
    # long-lived branches
    - master
    - develop
    - next

  pull_request:
    branches:
      - "*"

jobs:
  yarncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - run: npm install -g yarn
      - run: yarn bootstrap
      - run: test -z "$(git diff)" || (echo 'Please run yarn and commit all changes to yarn.lock'; false)


  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        node-version: [10.x, 12.x, 14.x]
        env: [GETH=true, PACKAGES=true, INTEGRATION=true]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn
    - run: yarn bootstrap
    - run: ${{ matrix.env }} yarn ci
      env:
        CI: true
    - uses: 8398a7/action-slack@v1.1.1
      with:
        type: failure
        failedMenthon: ""
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: failure()

  slack_notification:
    needs: [yarncheck, build]
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: 8398a7/action-slack@v1.1.1
        continue-on-error: true
        with:
          type: success
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: github.event_name == 'pull_request' && !github.event.pull_request.head.repo.fork
